# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d70a4221a4c7f62e7b7f0a4bb387b8fb777b81b477910366aeb157139c7565409f8bca58d2e8dfe84a506eed1624a27422becf08b2130fd4e96212a1d6ab8e

test:
  secret_key_base: c68bb5daed8015386a9e4bfc66e36e2497ed05b6e7c8a0a362d8513de7adfa77dd13befe30b9bab5cee960b2d4369aab0a5f6cbb252ea4ddd7e47ae0147fed4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
